transaction/urls.py
# encoding: utf-8
from django.conf.urls import patterns, url
import django
from transaction.views import *;

urlpatterns = patterns(
	'',
	url(r'^files/(?P<pk>\d+)$', transaction_files, name='transaction-files'),
	url(r'^group_form_add', group_form_add, name='group-form-add'),
	url(r'^group_form_edit/(?P<pk>\d+)', group_form_edit, name='group-form-edit'),
	url(r'^field_add', field_add, name='field-add'),
	url(r'^field_edit/(?P<pk>\d+)', field_edit, name='field-edit'),
	url(r'^list_field', list_field, name='list-field'),
	url(r'^list_group_form', list_group_form, name='list-group-form'),
	url(r'^field_delete/(?P<pk>\d+)', field_delete, name='field-delete'),
	url(r'^group_form_delete/(?P<pk>\d+)', group_form_delete, name='group-form-delete'),

	url(r"^create_groupfield", create_groupfield, name="create_groupfield"),
	url(r"^edit_groupfield", edit_groupfield, name="edit_groupfield"),
	url(r"^delete_groupfield", delete_groupfield, name="delete_groupfield"),
	url(r"^groupfield_list", groupfield_list, name="groupfield_list"),
	url(r"^create_form", create_form, name="create_form"),
	url(r"^edit_form", edit_form, name="edit_form"),
	url(r"^delete_form", delete_form, name="delete_form"),
	url(r"^form_list", form_list, name="form_list"),
)

website/urls.py
from django.conf.urls import patterns, url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from uploading.views import Dashboard, homeredirect

urlpatterns = patterns(
	"",
	url(r"^$", homeredirect),
	url(r'^admin/', include(admin.site.urls)),
	url(r"^dashboard", Dashboard.as_view(), name="dashboard"),
	url(r'^accounts/', include('allauth.urls')),
	url(r'^user/', include('userprofile.urls')),
	url(r'^upload/', include('uploading.urls')),
	url(r'^processing/', include('processing.urls')),
	url(r'^transaction/', include('transaction.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

#should remove url for customer

transaction/models.py
import os
import datetime
from django.db import models
from django.utils.translation import gettext_lazy as _
from userprofile.models import Company


class FieldType(models.Model):
	name = models.CharField(_('Field type'), max_length=250)

	def __unicode__(self):
		return self.name


class Field(models.Model):
	label = models.CharField(_('Label'), max_length=250)
	fieldtype = models.ForeignKey("FieldType", null=True, blank=True)
	description = models.TextField(_('Description'), blank=True)
	html = models.TextField(_('HTML'), blank=True)

	def __unicode__(self):
		return self.label

	@classmethod
	def add_field(cls, dict):
		if dict:
			field = Field.objects.create(**dict)
			field.save()
			return field

	@classmethod
	def get_field_by_id(cls, pk):
		return Field.objects.get(id=pk)

	@classmethod
	def update_field(cls, pk, dict):
		if dict:
			field = cls.get_field_by_id(pk)
			field.label = dict["label"]
			field.fieldtype = dict["fieldtype"]
			field.description = dict["description"]
			field.html = dict["html"]
			field.save()
			return field


class GroupFieldField(models.Model):
	index = models.IntegerField(_('Index'), default=0)
	field = models.ForeignKey("Field", null=True, blank=True)
	groupfield = models.ForeignKey("GroupField", null=True, blank=True)

	def __unicode__(self):
		return '%d' % self.index


class GroupField(models.Model):
	name = models.CharField(_('Name'), max_length=250)

	def __unicode__(self):
		return self.name


class FormField(models.Model):
	index = models.IntegerField(_('Index'), default=0)
	field = models.ForeignKey("Field", null=True, blank=True)
	form = models.ForeignKey("Form", null=True, blank=True)

	def __unicode__(self):
		return '%d' % self.index


class FormGroupField(models.Model):
	index = models.IntegerField(_('Index'), default=0)
	groupfield = models.ForeignKey("GroupField", null=True, blank=True)
	form = models.ForeignKey("Form", null=True, blank=True)

	def __unicode__(self):
		return '%d' % self.index


class GroupForm(models.Model):
	name = models.CharField(_('Name'), max_length=250)
	description = models.TextField(_('Description'), blank=True)
	html = models.TextField(_('HTML content'), blank=True)
	# icon = models.CharField(_('File path'), max_length=250, blank=True)
	icon = models.ImageField(_('File path'), blank=True, upload_to='icon/%d/%m/%Y')

	def __unicode__(self):
		return self.name

	@classmethod
	def get_group_form_by_id(cls, pk):
		return GroupForm.objects.get(id=pk)

	@classmethod
	def add_group_form(cls, dict):
		if dict:
			group_form = GroupForm.objects.create(**dict)
			group_form.save()
			return group_form

	@classmethod
	def update_group_form(cls, pk, dict):
		if dict:
			group_form = cls.get_group_form_by_id(pk)
			group_form.name = dict["name"]
			group_form.description = dict["description"]
			group_form.html = dict["html"]
			group_form.icon = dict["icon"]
			group_form.save()
			return group_form


class Form(models.Model):
	name = models.CharField(_('Name'), max_length=250)
	company = models.ForeignKey("userprofile.Company", null=True, blank=True)
	groupform = models.ForeignKey("GroupForm", null=True, blank=True)

	def __unicode__(self):
		return self.name

transaction/forms.py
from django.forms import ModelForm
from .models import GroupForm, Field


class GroupFormForm(ModelForm):
	class Meta:
		model = GroupForm

	def __init__(self, *args, **kwargs):
		super(GroupFormForm, self).__init__(*args, **kwargs)
		for field in self.base_fields.values():
			field.widget.attrs['placeholder'] = field.label


class FieldForm(ModelForm):
	class Meta:
		model = Field

	def __init__(self, *args, **kwargs):
		super(FieldForm, self).__init__(*args, **kwargs)
		for field in self.base_fields.values():
			field.widget.attrs['placeholder'] = field.label

transaction/views.py
import json
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _
from django.views.generic.edit import FormView
from django.views.generic import ListView, DeleteView
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect
from operator import itemgetter
import datetime
from decimal import *

from uploading.models import *
from transaction.models import *
from userprofile.models import *
from .forms import GroupFormForm, FieldForm
from allauth.account.utils import get_next_redirect_url
from userprofile.decorators import permission_access_page_required
from uploading.tools import filesizeformat


class GroupFormView(FormView):
	form_class = GroupFormForm
	redirect_field_name = "next"

	def get_initial(self):
		initial = super(GroupFormView, self).get_initial()
		return initial

	def get_success_url(self):
		ret = (get_next_redirect_url(
			self.request,
			self.redirect_field_name
		) or self.success_url)

		return ret

	def form_valid(self, form):
		return super(GroupFormView, self).form_valid(form)

	@staticmethod
	def get_group_form_dictionary(form):
		group_form = {
			"name": form.cleaned_data.get("name"),
			"description": form.cleaned_data.get("description"),
			"html": form.cleaned_data.get("html"),
			"icon": form.cleaned_data.get("icon"),
		}
		return group_form


class GroupFormAddView(GroupFormView):
	template_name = "transaction/group_form_form.html"
	messages = {
		"user_added": {
			"level": messages.SUCCESS,
			"text": _("New group form is added")
		},
	}

	def get_context_data(self, **kwargs):
		context = super(GroupFormAddView, self).get_context_data(**kwargs)
		context["action"] = "add"
		return context

	def form_valid(self, form):
		group_form = GroupForm.add_group_form(self.get_group_form_dictionary(form))
		self.success_url = "/transaction/group_form_edit/"+str(group_form.id)
		if group_form:
			messages.add_message(
				self.request,
				self.messages["user_added"]["level"],
				"SUCCESS: %s - GroupForm has been created successfully!" % (group_form.name)
			)

		return super(GroupFormAddView, self).form_valid(form)


class GroupFormEditView(GroupFormView):
	template_name = "transaction/group_form_form.html"
	messages = {
		"user_added": {
			"level": messages.SUCCESS,
			"text": _("Updated success")
		},
	}

	def delete(self, request, *args, **kwargs):
		if self.request.is_ajax():
			group_form = GroupForm.objects.get(id=self.kwargs.get('pk'))
			group_form.icon.delete()
			return HttpResponse(status=202)

	def get_context_data(self, **kwargs):
		context = super(GroupFormEditView, self).get_context_data(**kwargs)
		group_form = GroupForm.objects.get(id=self.kwargs.get('pk'))
		context["groupform_id"] = group_form.id
		context["action"] = "edit"
		if group_form.icon:
			context["icon_path"] = group_form.icon
		return context

	def get_initial(self):
		try:
			initial = super(GroupFormEditView, self).get_initial()
			group_form_id = self.kwargs.get("pk", None)
			group_form = GroupForm.get_group_form_by_id(group_form_id)
			initial["name"] = group_form.name
			initial["description"] = group_form.description
			initial["html"] = group_form.html
			initial["icon"] = group_form.icon
			return initial
		except ObjectDoesNotExist:
			raise ObjectDoesNotExist

	def form_valid(self, form):
		group_form_id = self.kwargs.get("pk", None)
		group_form = GroupForm.objects.get(id=self.kwargs.get('pk'))
		if group_form_id is not None:
			if group_form.icon and "icon" in form.changed_data:
				group_form.icon.delete()
			group_form = GroupForm.update_group_form(group_form_id, self.get_group_form_dictionary(form))
			messages.add_message(
				self.request,
				self.messages["user_added"]["level"],
				"SUCCESS: %s - GroupForm has been updated successfully!" % (group_form.name)
			)
			self.success_url = "/transaction/group_form_edit/"+str(group_form_id)

		return super(GroupFormEditView, self).form_valid(form)


class FilesProcessView(ListView):
	model = FileUpload
	paginate_by = 20
	template_name = "transaction/list_file_form.html"

	def get_context_data(self, **kwargs):
		context = super(FilesProcessView, self).get_context_data(**kwargs)
		form_info = Form.objects.get(id=self.kwargs.get("pk", None))
		form_name = form_info.name
		group_form_name = form_info.groupform.name

		new_object_list = []
		for object in context["object_list"]:
			new_object = {}
			new_object["id"] = object.id
			new_object["name"] = object.name
			new_object["file"] = object.file
			new_object["note"] = object.note.replace("\r\n", " ")
			new_object["form"] = object.form
			new_object["upload_date"] = object.upload_date.strftime("%b %d, %Y, %I:%M %p")
			new_object["user_process"] = object.user_process
			new_object["process_date"] = ""
			if object.process_date:
				new_object["process_date"] = object.process_date.strftime("%b %d, %Y, %I:%M %p")

			file_tiff = FileTiff.objects.filter(fileupload=object)
			file_tiff_process = FileTiff.objects.filter(
				fileupload=object,
				status=1
			)

			if len(file_tiff) > 0:
				new_object["file_process"] = "%s/%s Pages" % (len(file_tiff_process), len(file_tiff))
				new_object["progress"] = Decimal(len(file_tiff_process))/Decimal(len(file_tiff))*100
				new_object["is_finish_process"] = True if len(file_tiff_process) == len(file_tiff) else False
				new_object["is_start_process"] = True if len(file_tiff_process) > 0 else False
				new_object["is_exist_file_tiff"] = True
			else:
				new_object["file_process"] = "There are not any tiff file"
				new_object["progress"] = ""
				new_object["is_finish_process"] = False
				new_object["is_start_process"] = False
				new_object["is_exist_file_tiff"] = False

			new_object_list.append(new_object)

		context["new_object_list"] = new_object_list
		context['breadcrumb'] = [group_form_name, form_name]
		context["form_name"] = form_name
		context['form_id'] = form_info.id
		return context

	def get_queryset(self):
		query_dict = {}
		if self.request.GET.get("q"):
			query_dict["name__icontains"] = self.request.GET.get("q")

		user = self.request.user
		forms_id = [str(form.id) for form in user.user_profile.permission.all()]
		form_id = str(self.kwargs.get("pk", None))
		set_form_id = 0

		try:
			if form_id in forms_id:
				set_form_id = form_id

			queryset = FileUpload.objects.filter(
				form__id=set_form_id,
				**query_dict
			).order_by("-upload_date")
		except ValueError:
			raise ValueError("You do not have permissions to access this form")

		return queryset

	def render_to_response(self, context, **kwargs):
		if self.request.is_ajax():
			object_json = {}
			object_json["items"] = new_object_list = []

			for object in context["object_list"]:
				new_object = {}
				new_object["id"] = object.id
				new_object["name"] = object.name
				new_object["file"] = object.file.name
				new_object["size"] = filesizeformat(object.file.size)
				new_object["note"] = object.note.replace("\r\n", " ")
				new_object["form"] = object.form.name
				new_object["form_id"] = object.form.id
				new_object["upload_date"] = object.upload_date.strftime("%b %d, %Y, %I:%M %p")

				new_object["process_date"] = ""
				if object.process_date:
					new_object["process_date"] = object.process_date.strftime("%b %d, %Y, %I:%M %p")

				file_tiff = FileTiff.objects.filter(fileupload=object)
				file_tiff_process = FileTiff.objects.filter(
					fileupload=object,
					status=1
				)
				if len(file_tiff) > 0:
					new_object["file_process"] = "%s/%s Pages" % (len(file_tiff_process), len(file_tiff))
					new_object["progress"] = int(Decimal(len(file_tiff_process))/Decimal(len(file_tiff))*100)
					new_object["is_finish_process"] = True if len(file_tiff_process) == len(file_tiff) else False
					new_object["is_start_process"] = True if len(file_tiff_process) > 0 else False
					new_object["is_exist_file_tiff"] = True
				else:
					new_object["file_process"] = "There are not any tiff file"
					new_object["progress"] = ""
					new_object["is_finish_process"] = False
					new_object["is_start_process"] = False
					new_object["is_exist_file_tiff"] = False

				new_object_list.append(new_object)

			object_json["items"] = new_object_list
			object_json["has_next"] = False
			object_json["next_page"] = 0
			if context["page_obj"].has_next():
				object_json["has_next"] = True
				object_json["next_page"] = context["page_obj"].next_page_number()

			return HttpResponse(json.dumps(object_json), content_type='application/json')
		else:
			return super(FilesProcessView, self).render_to_response(context, **kwargs)


transaction_files = permission_access_page_required(FilesProcessView.as_view())

group_form_add = permission_access_page_required(GroupFormAddView.as_view())

group_form_edit = permission_access_page_required(GroupFormEditView.as_view())


class FieldView(FormView):
	form_class = FieldForm
	redirect_field_name = "next"

	def get_initial(self):
		initial = super(FieldView, self).get_initial()
		return initial

	def get_success_url(self):
		ret = (get_next_redirect_url(
			self.request,
			self.redirect_field_name
		) or self.success_url)

		return ret

	def form_valid(self, form):
		return super(FieldView, self).form_valid(form)

	@staticmethod
	def get_field_dictionary(form):
		field = {
			"label": form.cleaned_data.get("label"),
			"fieldtype": form.cleaned_data.get("fieldtype"),
			"description": form.cleaned_data.get("description"),
			"html": form.cleaned_data.get("html"),
		}
		return field


class FieldAddView(FieldView):
	template_name = "transaction/field_form.html"
	messages = {
		"user_added": {
			"level": messages.SUCCESS,
			"text": _("New field has been created successfully!")
		},
	}

	def get_context_data(self, **kwargs):

transaction/templates/create_groupfield.html
{% extends "base.html" %}
{% load staticfiles %}
{% load url from future %}

{% block breadcrumbs %}
	<li>Transaction</li>
	<li>Create new GroupField</li>
{% endblock %}

{% block extra_style %}
	<style type="text/css">
		.form-horizontal .control-label{text-align: left}
		.multiple-select {width: 250px; line-height: 1.5cm; padding: 3px;}
		#demo fieldset div {float: left; width: 30%; clear: none;}
		#demo fieldset a {text-decoration: none; font-weight: bold;}
		.page-header{margin: 0 0 20px}
		.page-header h1{margin-left: 0px}
		#demo input{width: 80%}
	</style>
{% endblock %}

{% block content %}
	<div class="row">
		<form class="form-horizontal" method="post" name="form1" id="demo" action="{% url 'create_groupfield' %}">
			<div class="col-xs-12">
				<div class="page-header">
					<h1>Create new GroupField</h1>
				</div>
				<div class="col-xs-8">
					<div class="form-group">
						<label class="col-sm-2 control-label no-padding-right">GroupField name: <span class="red">*</span>:</label>
						<div class="col-sm-9">
							<input placeholder="GroupField name" size="10" name="groupfield_name" type="text">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 control-label no-padding-right">Add Field:</label>
						<div class="col-sm-10">
							<div style="float: left">
								<select style="height: 150px; width: 200px" name="selectfrom" id="select-from" multiple="multiple" size="6" class="multiple-select">
									{% for field in field_list %}
										<option value="{{field.id}}" name="{{field.id}}">{{field.label}}</option>
									{% endfor %}
								</select>
							</div>
							<div style="float: left;height: 170px; width: 120px">
								<center>
									<a title="Add" style="padding:2px; width: 90px; margin-left: 2px; font-size: 12px" class="btn btn-success" href="javascript:void(0);" id="btn-add"><span><i class="glyphicon glyphicon-arrow-right"></i></span></a>
									<br>
									<a title="Remove" style="padding:2px; width: 90px; margin-top: 11px; font-size: 12px" class="btn btn-danger" href="javascript:void(0);" id="btn-remove"><span><i class="glyphicon glyphicon-arrow-left"></i></span></a>
									<br>
									<a title="Move Up" style="padding:2px; width: 90px; margin-top: 11px; font-size: 12px; padding-top: 4px; padding-bottom: 4px" class="btn btn-white" id="btn-up"><span><i class="glyphicon glyphicon-arrow-up"></i></span></a>
									<br>
									<a title="Move Down" style="padding:2px; width: 90px; margin-top: 11px; font-size: 12px; padding-top: 4px; padding-bottom: 4px" class="btn btn-white" id="btn-down"><span><i class="glyphicon glyphicon-arrow-down"></i></span></a>
								</center>
							</div>
							<div style="float: left;">
								<select style="height: 150px; width: 200px" name="selectto" id="select-to" multiple="multiple" size="6" class="multiple-select">
								{% for field in selected_field_list %}
								<option value="{{field.id}}" name="{{field.id}}">{{field.label}}</option>
								{% endfor %}
								</select>
							</div>
						</div>
					</div>
				</div>
				<div class="clearfix form-actions" style="float:left; width: 100%">
					<div class="">
						<button type="submit" onclick="selectAll();" class="btn btn-info button-submit" type="button">
							<i class="icon-ok bigger-110"></i>
							Submit
						</button>

						&nbsp; &nbsp; &nbsp;
						<button class="btn" type="reset">
							<i class="icon-undo bigger-110"></i>
							Reset
						</button>

						&nbsp; &nbsp; &nbsp;
						<span class="loading-span" style="font-size: 14px; display: none"><img width="30px" src="{% static 'bootstrap/images/loading.gif' %}"> Please wait...</span>
					</div>
				</div>
			</div>
		</form>
	</div>
{% endblock %}

{% block extra_script %}
	<script>
		var arrSelected = [];
		{% for field in selected_field_list %}
			arrSelected.push({
				'name': '{{field.label}}',
				'value': {{field.id}},
				'selected': false
			});
		{% endfor %}
	</script>
	<script src="{% static "bootstrap/js/add_field_to_groupfield.js" %}"></script>
{% endblock %}

transaction/templates/edit_groupfield.html
{% extends "base.html" %}
{% load staticfiles %}
{% load url from future %}

{% block breadcrumbs %}
	<li>Transaction</li>
	<li>Edit GroupField</li>
{% endblock %}

{% block extra_style %}
	<style type="text/css">
		.form-horizontal .control-label{text-align: left}
		.multiple-select {width: 250px; line-height: 1.5cm; padding: 3px;}
		#demo fieldset div {float: left; width: 30%; clear: none;}
		#demo fieldset a {text-decoration: none; font-weight: bold;}
		.page-header{margin: 0 0 20px}
		.page-header h1{margin-left: 0px}
		#demo input{width: 80%}
	</style>
{% endblock %}

{% block content %}
{#	<div>#}
{#		<form method="post" name="form1" id="demo" action="">#}
{#		  <fieldset>#}
{#		  	<div><strong>GroupField name: </strong><input size="10" name="groupfield_name" type="text" value="{{groupfield_name}}"></div>#}
{#			<div><input name="groupfield_id" type="hidden" value="{{groupfield_id}}"></div>#}
{#			<div class="focus">#}
{#			<select name="selectfrom" id="select-from" multiple="multiple" size="6" class="multiple-select">#}
{#				{% for field in field_list %}#}
{#					<option value="{{field.id}}" name="{{field.id}}">{{field.label}}</option>#}
{#				{% endfor %}#}
{#			</select>#}
{#		  </div>#}
{#		  <div>#}
{#			<a href="javascript:void(0);" id="btn-add"><span>Add</span></a>#}
{#			<br>#}
{#			<br>#}
{#			<a href="javascript:void(0);" id="btn-remove"><span>Remove</span></a>#}
{#		  </div>#}
{#		  <div class="focus">#}
{#			<select name="selectto" id="select-to" multiple="multiple" size="6" class="multiple-select">#}
{#				{% for field in selected_field_list %}#}
{#				<option value="{{field.id}}" name="{{field.id}}">{{field.label}}</option>#}
{#				{% endfor %}#}
{#			</select>#}
{#		  </div>#}
{#			<div style="float: right"><button style="border-radius: 5px" type="submit" onclick="selectAll();">Save</button></div>#}
{#		  </fieldset>#}
{#		</form>#}
{#	  </div>#}


	<div class="row">
		<form class="form-horizontal" method="post" name="form1" id="demo" action="">
			<div class="col-xs-12">
				<div class="page-header">
					<h1>Edit GroupField</h1>
				</div>
				<div class="col-xs-8">
					<div class="form-group">
						<label class="col-sm-2 control-label no-padding-right">GroupField name: <span class="red">*</span>:</label>
						<div class="col-sm-9">
							<input placeholder="GroupField name" size="10" name="groupfield_name" type="text" value="{{groupfield_name}}">
							<input name="groupfield_id" type="hidden" value="{{groupfield_id}}">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 control-label no-padding-right">Add Field:</label>
						<div class="col-sm-9">
							<div style="float: left">
								<select style="height: 150px; width: 200px" name="selectfrom" id="select-from" multiple="multiple" size="6" class="multiple-select">
									{% for field in field_list %}
										<option value="{{field.id}}" name="{{field.id}}">{{field.label}}</option>
									{% endfor %}
								</select>
							</div>
							<div style="float: left;height: 170px; width: 120px">
								<center>
									<a title="Add" style="padding:2px; width: 90px; margin-left: 2px; font-size: 12px" class="btn btn-success" href="javascript:void(0);" id="btn-add"><span><i class="glyphicon glyphicon-arrow-right"></i></span></a>
									<br>
									<a title="Remove" style="padding:2px; width: 90px; margin-top: 11px; font-size: 12px" class="btn btn-danger" href="javascript:void(0);" id="btn-remove"><span><i class="glyphicon glyphicon-arrow-left"></i></span></a>
									<br>
									<a title="Move Up" style="padding:2px; width: 90px; margin-top: 11px; font-size: 12px; padding-top: 4px; padding-bottom: 4px" class="btn btn-white" id="btn-up"><span><i class="glyphicon glyphicon-arrow-up"></i></span></a>
									<br>
									<a title="Move Down" style="padding:2px; width: 90px; margin-top: 11px; font-size: 12px; padding-top: 4px; padding-bottom: 4px" class="btn btn-white" id="btn-down"><span><i class="glyphicon glyphicon-arrow-down"></i></span></a>
								</center>
							</div>
							<div style="float: left;">
								<select style="height: 150px; width: 200px" name="selectto" id="select-to" multiple="multiple" size="6" class="multiple-select">
									{% for field in selected_field_list %}
										<option value="{{field.id}}" name="{{field.id}}">{{field.label}}</option>
									{% endfor %}
								</select>
							</div>
						</div>
					</div>
				</div>
				<div class="clearfix form-actions" style="float:left; width: 100%">
					<div class="">
						<button type="submit" onclick="selectAll();" class="btn btn-info button-submit" type="button">
							<i class="icon-ok bigger-110"></i>
							Submit
						</button>

						&nbsp; &nbsp; &nbsp;
						<button class="btn" type="reset">
							<i class="icon-undo bigger-110"></i>
							Reset
						</button>

						&nbsp; &nbsp; &nbsp;
						<button class="btn btn-danger btn-delete" href="{% url 'delete_groupfield' %}?action=delete&groupfield_id={{ request.GET.groupfield_id }}">
							<i class="icon-remove bigger-110"></i>
							Delete
						</button>

						&nbsp; &nbsp; &nbsp;
						<span class="loading-span" style="font-size: 14px; display: none"><img width="30px" src="{% static 'bootstrap/images/loading.gif' %}"> Please wait...</span>
					</div>
				</div>
			</div>
		</form>
	</div>
{% endblock %}

{% block extra_script %}
	<script>
		var arrSelected = [];
		{% for field in selected_field_list %}
			arrSelected.push({
				'name': '{{field.label}}',
				'value': {{field.id}},
				'selected': false
			});
		{% endfor %}
	</script>
	<script src="{% static "bootstrap/js/add_field_to_groupfield.js" %}"></script>
{% endblock %}